#!/bin/sh

growl_notify () {
	growlnotify -m "$1" -n irssi ${opt_sticky:+--sticky} \
		${opt_icon:+-i $opt_icon} \
		${opt_title:+"$opt_title"}
}

libnotify_notify () {
	notify-send ${opt_timeout:+-t $opt_timeout} \
		${opt_icon:+-i $opt_icon} "${opt_title}" "$1"
}

while [ $# -gt 0 ]; do
	case $1 in
		(--sticky|-S)	opt_sticky=1
				;;
		(--title|-T)	shift
				opt_title=$1
				;;
		(--timeout|-t)	shift
				opt_timeout=$1
				;;
		(--icon|-i)	shift
				opt_icon=$1
				;;
		(--)		shift
				break
				;;

		(-*)		echo "ERROR: Unknown option: $1" >&2
				exit 2
				;;

		(*)		break
				;;
	esac

	shift
done

message="$*"

case $(uname -s) in
	(Darwin)	growl_notify "$message"
			;;

	(Linux)		libnotify_notify "$message"
			;;
esac

